# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-20 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grqx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QX', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('xh', models.IntegerField(primary_key=True, serialize=False)),
                ('info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jbxx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xh', models.CharField(max_length=20, verbose_name='学号')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='姓名')),
                ('sex', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('yx', models.CharField(blank=True, max_length=20, null=True, verbose_name='院系')),
                ('zy', models.CharField(blank=True, max_length=20, null=True, verbose_name='专业')),
                ('nj', models.CharField(blank=True, max_length=20, null=True, verbose_name='年级')),
                ('jg', models.CharField(blank=True, max_length=20, null=True, verbose_name='籍贯')),
                ('bm', models.CharField(blank=True, max_length=20, null=True, verbose_name='部门')),
                ('zb', models.CharField(blank=True, max_length=20, null=True, verbose_name='组')),
                ('qq', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('jy', models.TextField(blank=True, null=True, verbose_name='经验')),
                ('tc', models.TextField(blank=True, null=True, verbose_name='特长')),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('join_time', models.DateTimeField(verbose_name='加入时间')),
                ('SFKY', models.CharField(blank=True, max_length=20, null=True, verbose_name='是否考研')),
                ('SFQG', models.CharField(blank=True, max_length=20, null=True, verbose_name='是否勤工')),
                ('YHKH', models.CharField(blank=True, max_length=20, null=True, verbose_name='银行卡号')),
                ('QX', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='member.Grqx', verbose_name='权限')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
